# Generated by Django 4.1.5 on 2023-05-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmdb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.AlterModelTable(
            name='company',
            table='tbl_hm_config',
        ),
    ]
