# Generated by Django 4.1.5 on 2023-05-09 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmdb', '0002_delete_authuser_alter_company_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tblallowapp',
            table='erpdb_tblallowapp',
        ),
        migrations.AlterModelTable(
            name='tbluserauth',
            table='erpdb_tbluserauth',
        ),
        migrations.CreateModel(
            name='EmpmasIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_cde', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_income', models.FloatField(blank=True, null=True)),
                ('emp_cum_income', models.FloatField(blank=True, null=True)),
                ('emp_soc', models.FloatField(blank=True, null=True)),
                ('emp_cum_soc', models.FloatField(blank=True, null=True)),
                ('emp_tax', models.FloatField(blank=True, null=True)),
                ('emp_cum_tax', models.FloatField(blank=True, null=True)),
                ('em_bf_inc', models.FloatField(blank=True, null=True)),
                ('em_bf_soc', models.FloatField(blank=True, null=True)),
                ('em_bf_tax', models.FloatField(blank=True, null=True)),
                ('empmas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmdb.empmas')),
            ],
            options={
                'db_table': 'empmasincome',
            },
        ),
    ]
