# Generated by Django 4.1.5 on 2023-05-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmdb', '0003_alter_tblallowapp_table_alter_tbluserauth_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empmasincome',
            table=None,
        ),
    ]
