# Generated by Django 4.1.5 on 2023-05-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmdb', '0004_alter_empmasincome_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empmasincome',
            options={'managed': False},
        ),
    ]
