# Generated by Django 4.1.5 on 2023-05-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmdb', '0005_alter_empmasincome_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empmasincome',
            table='empmas_income',
        ),
    ]
