# Generated by Django 4.1.3 on 2023-06-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmdb', '0006_alter_empmasincome_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpmasResign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_cde', models.CharField(blank=True, max_length=50, null=True)),
                ('resign_require_date', models.DateField()),
                ('resign_effective_date', models.DateField()),
                ('resign_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'empmas_resign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpTranLeave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_cde', models.CharField(blank=True, max_length=50, null=True)),
                ('leavedate', models.CharField(blank=True, max_length=50, null=True)),
                ('leavecode', models.CharField(blank=True, max_length=10, null=True)),
                ('starttime', models.CharField(blank=True, max_length=20, null=True)),
                ('endtime', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('pay', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'emp_tranleave',
                'managed': False,
            },
        ),
    ]
