# Generated by Django 4.1.5 on 2023-07-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmdb', '0007_empmasresign_emptranleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ta_date', models.DateTimeField(blank=True, null=True)),
                ('timein', models.CharField(blank=True, max_length=20, null=True)),
                ('timeout', models.CharField(blank=True, max_length=20, null=True)),
                ('workdate', models.CharField(blank=True, max_length=20, null=True)),
                ('shift', models.CharField(blank=True, db_column='shiftcode', max_length=20, null=True)),
                ('pay', models.CharField(blank=True, max_length=1, null=True)),
                ('holiday', models.CharField(blank=True, max_length=1, null=True)),
                ('leavecode', models.CharField(blank=True, max_length=10, null=True)),
                ('numlate', models.IntegerField(blank=True, db_column='num_late', null=True)),
                ('numot', models.IntegerField(blank=True, db_column='ot_time', null=True)),
                ('numoutbf', models.IntegerField(blank=True, db_column='num_betimeout', null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks_other', models.CharField(blank=True, max_length=200, null=True)),
                ('ka', models.CharField(blank=True, max_length=30, null=True)),
                ('ot', models.CharField(blank=True, max_length=20, null=True)),
                ('ot_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'emptime_mast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='empstatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workdate', models.CharField(blank=True, max_length=20, null=True)),
                ('n_work', models.IntegerField()),
                ('n_leave', models.IntegerField()),
                ('n_absent', models.IntegerField()),
                ('n_late', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TblShift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shift', models.CharField(blank=True, db_column='shiftcode', max_length=20, null=True, unique=True)),
                ('shiftname', models.CharField(blank=True, max_length=50, null=True)),
                ('starttime', models.CharField(blank=True, max_length=20, null=True)),
                ('endtime', models.CharField(blank=True, max_length=20, null=True)),
                ('ot_st', models.CharField(blank=True, max_length=20, null=True)),
                ('ot_end', models.CharField(blank=True, max_length=20, null=True)),
                ('in_shift_st', models.CharField(blank=True, max_length=20, null=True)),
                ('in_shift_end', models.CharField(blank=True, max_length=20, null=True)),
                ('out_shift_st', models.CharField(blank=True, max_length=20, null=True)),
                ('out_shift_end', models.CharField(blank=True, max_length=20, null=True)),
                ('break_st', models.CharField(blank=True, max_length=20, null=True)),
                ('break_end', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_shift',
            },
        ),
    ]
