# Generated by Django 4.1.5 on 2023-08-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmdb', '0008_emptime_empstatistic_tblshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='empstatistic',
            name='dayofweek',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
